<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-LD88KNN" failures="1" tests="3" name="Test" time="89.15" errors="0" timestamp="2022-10-29T17:52:31 PDT">
  <testcase classname="com.testLayer.LoginPageTest" name="logintest" time="5.547"/>
  <testcase classname="com.testLayer.BuyScenarioTest" name="BuyShareWithCustomLimit" time="16.871">
    <failure type="java.lang.AssertionError" message="expected [Limit Order Created Successfully12456] but found [Limit Order Created Successfully]">
      <![CDATA[java.lang.AssertionError: expected [Limit Order Created Successfully12456] but found [Limit Order Created Successfully]
at com.testLayer.BuyScenarioTest.BuyShareWithCustomLimit(BuyScenarioTest.java:51)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- BuyShareWithCustomLimit -->
  <testcase classname="com.testLayer.BuyScenarioTest" name="buyShareforLongTerm" time="10.813"/>
</testsuite> <!-- Test -->
